name: Weather Logger

on: [push]

jobs:
  log-weather:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install requests

    - name: Run weather script
      run: python main.py
